spring.application.name=KinoXp
spring.profiles.active=dev

# H2 Database Configuration
#spring.datasource.url=jdbc:h2:mem:kinodb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# Mysql Database Configuration
#spring.datasource.url=jdbc:mysql://localhost:3607/${MYSQL_DATABASE:Kinodb}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=${MYSQL_USER:Freja}
#spring.datasource.password=${MYSQL_PASSWORD:secret}

spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
management.endpoints.web.exposure.include=health