
name: KinoXP CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  java-test:
    uses: ./.github/workflows/Java_tets_with_maven.yml

  docker-ci:
    needs: java-test
    uses: ./.github/workflows/publish.yaml

